apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
  namespace: datapipe
spec:
  ingressClassName: nginx
  rules:
    - host: metabase.pi3.mk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 80
  tls:
  - secretName: minikube-tls
    hosts:
      - metabase.pi3.mk
