apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmetadata-ingress
  namespace: datapipe
spec:
  ingressClassName: nginx
  rules:
    - host: metadata.pi3.mk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgresql # TODO: openmetadata
                port:
                  number: 5432 # TODO: 8585
  tls:
  - secretName: minikube-tls
    hosts:
      - metadata.pi3.mk
