repositories:
- name: memphis
  url: https://k8s.memphis.dev/charts/
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: metabase
  url: https://pmint93.github.io/helm-charts
- name: cert-manager
  url: https://charts.jetstack.io
- name: sigstore
  url: https://sigstore.github.io/helm-charts
- name: ory
  url: https://k8s.ory.sh/helm/charts
- name: teleport
  url: https://charts.releases.teleport.dev

# Add new components here (e.g. whatever charts you want installed)
releases:
- name: cert-manager
  namespace: cert-manager
  createNamespace: true
  chart: cert-manager/cert-manager
  values:
    - cert-manager.values.yaml
- name: fulcio
  namespace: sigstore
  createNamespace: true
  chart: sigstore/fulcio
  values:
    - fulcio.values.yaml
- name: rekor
  namespace: sigstore
  createNamespace: true
  chart: sigstore/rekor
  values:
    - rekor.values.yaml
- name: trillian
  namespace: sigstore
  createNamespace: true
  chart: sigstore/trillian
  values:
    - trillian.values.yaml
- name: tsa
  namespace: sigstore
  createNamespace: true
  chart: sigstore/tsa
  values:
    - tsa.values.yaml
- name: tsa
  namespace: sigstore
  createNamespace: true
  chart: sigstore/tsa
  values:
    - tsa.values.yaml

# https://k8s.ory.sh/helm/
# https://github.com/ory/k8s
- name: kratos
  namespace: ory
  createNamespace: true
  chart: ory/kratos
  values:
    - kratos.values.yaml
- name: keto
  namespace: ory
  createNamespace: true
  chart: ory/keto
  values:
    - keto.values.yaml
- name: hydra
  namespace: ory
  createNamespace: true
  chart: ory/hydra
  values:
    - hydra.values.yaml
- name: oathkeeper
  namespace: ory
  createNamespace: true
  chart: ory/oathkeeper
  values:
    - oathkeeper.values.yaml

- name: teleport-operator
  namespace: teleport
  createNamespace: true
  chart: teleport/teleport-operator
  values:
    - teleport-operator.values.yaml
- name: teleport-access-graph
  namespace: teleport
  createNamespace: true
  chart: teleport/teleport-access-graph
  values:
    - teleport-access-graph.values.yaml
- name: teleport-cluster
  namespace: teleport
  createNamespace: true
  chart: teleport/teleport-cluster
  values:
    - teleport-cluster.values.yaml
- name: teleport-plugin-slack
  namespace: teleport
  createNamespace: true
  chart: teleport/teleport-plugin-slack
  values:
    - teleport-plugin-slack.values.yaml
