repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

# Add new components here (e.g. whatever charts you want installed)
releases:
- name: postgresql
  namespace: datapipe
  createNamespace: true
  chart: bitnami/postgresql
  version: 15.5.5
  wait: true
  values:
    - ./values/postgresql.yaml
